---
date: 
external_link: 
image:
  caption: Cases over over last 2 Weeks
  focal_point: Smart
summary: Cases by County last 2 Weeks
tags:

title: Cases by County last 2 Weeks
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "static")
data1 <- read.csv("https://opendata-geohive.hub.arcgis.com/datasets/d9be85b30d7748b5b7c09450b8aede63_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D")
cso <- read.csv("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/counties_population_cso_2016.csv")

n <- nrow(data1)

data1$Date <- as.character(data1$TimeStamp)
data1$Date <- substr(data1$Date, 1, 10)
data1$Date <- as.Date(data1$Date, "%Y/%m/%d")
the.date <- data1$Date[n]




```
<br><br><br><br>

Breaking down the data to the level of cases per county over the last 2 weeks allows us to observe the current infection hotspots nationwide in a manner which is obscured when viewing the cumulative cases to date per county. Updated as of `r the.date`.

<br><br><br><br>


```{r, warning=FALSE, message=FALSE, echo=FALSE, include=TRUE}

data1 <- read.csv("https://opendata-geohive.hub.arcgis.com/datasets/d9be85b30d7748b5b7c09450b8aede63_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D")
cso <- read.csv("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/counties_population_cso_2016.csv")

n <- nrow(data1)

data1$Date <- as.character(data1$TimeStamp)
data1$Date <- substr(data1$Date, 1, 10)
data1$Date <- as.Date(data1$Date, "%Y/%m/%d")
the.date <- data1$Date[n]


library(sf)
library(tidyverse)
library(raster)
library(dplyr)
library(spData)
library(tmap)    # for static and interactive maps
library(csodata)

shp <- cso_get_geo("ac")
a<- data.frame(data1$Date, data1$CountyName, data1$ConfirmedCovidCases)
b <- reshape(a, direction="wide", idvar="data1.Date", timevar="data1.CountyName")



counties_start <- grep("data1.ConfirmedCovidCases.Carlow", colnames(b))
counties_stop <- grep("data1.ConfirmedCovidCases.Wicklow", colnames(b))

#kept last 14 days
counties <- tibble(b[which(b$data1.Date >= the.date -14 ), counties_start:counties_stop])
counties1 <- as.data.frame(counties)
N<- nrow(counties1)

counties1<- sapply(counties1,as.numeric)
counties2 <- counties1[N,] - counties1[N-13,]

counties3 <- data.frame(t(counties2[]))

counties3 <- data.frame(r1=names(counties3), t(counties3))
colnames(counties3)[2] <- "cases"
colnames(counties3)[1] <- "county_doh"

counties3$county_doh <- substring(counties3$county_doh,27)
counties3$county_doh <- tolower(counties3$county_doh)
 



counties3[,1] <- sub("cases_", "", counties3[,1])
counties3$cases <- as.numeric(counties3$cases)



county_cases <- merge(cso, counties3, by="county_doh")

county_cases$cases_per_mil <- 1000000*county_cases$cases/county_cases$pop

names(shp)[8] <- "county"
shp$county[20]="Dun Laoghaire-Rathdown"
county_cases$county[8]="Dun Laoghaire-Rathdown"

merged_cases <- merge(shp, county_cases, by="county")

tm_shape(merged_cases) + tm_fill(col="cases_per_mil", style = "pretty", title=c(paste("Cases per million", the.date))) + tm_borders() + tm_layout(asp = 1.28)          

```   
                

