---
title: "Covid-related ICU Admissions"
author: "Frank Moriarty and Ciaran Prendergast"
date: "5/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Covid-Related ICU Admissions

The **Intensive Care Units** in Ireland saw peak patient influx in late March - early April, and from late April, the daily percentage increase in ICU admissions has dropped substantially (note: percentages below 0% relate to days where validation of data led to a decrease in the reported overall number of cases admitted to ICU).
<br><br><br><br>
```{r, include=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(RCurl)
x <- getURL("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/doh_covid_ie_cases_analysis.csv")
data1 <- read.csv(text = x)
n <- nrow(data1)

#dervives column of new icu cases
data1$newicu[1] <- NA
if (n > 1) for(i in 2:n) data1$newicu[i] <- ( data1$cases_icu[i] - data1$cases_icu[i-1] )

#percentage of new cases
data1$newicu_per[1] <- NA
if (n > 1) for(i in 2:n) data1$newicu_per[i] <- ( 100*(data1$cases_icu[i] - data1$cases_icu[i-1])/data1$cases_icu[i-1] )

newicu <- as.numeric(data1$newicu)
newicu_per <- as.numeric(data1$newicu_per)
dates <- as.factor(data1$date)                   #this calls the dates
dates1 <- as.Date(dates, format= "%d-%b")
df <- data.frame(newicu_per,dates1,newicu)

ylim.prim <- c(0, 80)   
ylim.sec <- c(0, 50)

b <- diff(ylim.prim)/diff(ylim.sec)
a <- b*(ylim.prim[1] - ylim.sec[1])

plot <- ggplot(df, aes(dates1)) +
  geom_col(aes(y= newicu_per, color ="red")) +
  geom_line(aes(y = a + newicu*b, color = "blue")) +
  scale_y_continuous("% Increase on Total", sec.axis = sec_axis(~ (. - a)/b, name = "Daily Admissions")) +
  scale_x_date("Dates") +
  ggtitle("ICU Admissions in Ireland")

plot2 <- plot + scale_color_discrete(name = "", labels = c("Daily Admissions", "% Increase on Total")) +
  scale_fill_discrete(name = "", labels = "Increase on Total")

plot2 + theme(axis.text=element_text(size=12, face = "bold"),
              axis.title=element_text(size=14,face="bold"), plot.title = element_text(size=16, face = "bold"))


```
