---
title: "Evolution-of-the-Mode-of-Transmission"
author: "Frank Moriarty and Ciaran Prendergast"
date: "5/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Evolution of the Mode of Transmission

As travel restricions came into place the primary mode of infection has moved away from travel to infected regions and it became far more common to catch the virus through close contact with an infected person, such as a family-member; or through [Community Transmission](https://en.wikipedia.org/wiki/Transmission_(medicine)). 

```{r, include=TRUE, message=FALSE, warning=FALSE}
library(ggplot2)
library(scales)
library(tidyverse)
library(RCurl)
x <- getURL("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/doh_covid_ie_cases_analysis.csv")
data1 <- read.csv(text = x)
n <- nrow(data1)


dates <- as.factor(data1$date)
dates1 <- as.Date(dates, format= "%d-%b")
dataf <- data.frame(dates1,data1$percent_comm_trns,data1$percent_contact,data1$percent_travel)

plot <- ggplot(dataf, aes(dates1, data1$percent_comm_trns)) +
  geom_line(aes(color="tomato4")) +
  geom_line(aes(y = data1$percent_contact, color = "blue"))+
  geom_line(aes(y = data1$percent_travel, color = "green"))
  

  

plot2 <- plot + labs(title = "Evolution of the Mode of Transmission")+
 scale_y_continuous("% of All Infections", labels = percent_format(), limits=c(0,1))+
  scale_x_date("Date")

plot3<- plot2 + scale_color_discrete(name = "", labels = c("Community Transmission","Travel-Related","Close Contact"))


plot3 + theme(axis.text=element_text(size=12, face = "bold"),axis.title=element_text(size=14,face="bold"),plot.title= element_text(size=16, face="bold"))
  


```
<a href="#top">Back to top</a>
<br><br><br><br>

