---
title: "Infection Rate By County"
author: "Frank Moriarty and Ciaran Prendergast"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = FALSE)
rm(list=ls())
data1 <- read.csv("https://opendata-geohive.hub.arcgis.com/datasets/d8eb52d56273413b84b0187a4e9117be_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D")

n <- nrow(data1)

data1$Date <- as.character(data1$Date)
data1$Date <- substr(data1$Date, 1, 10)
data1$Date <- as.Date(data1$Date, "%Y/%m/%d")
the.date <- data1$Date[n]

```

## Counties most affected

As we can see in the map, **Dublin** and **Cavan** have suffered the highest relative proportion of cases, followed by Monaghan, Westmeath, Kildare and Wicklow. As of `r the.date` , it is mainly counties of the west that have been least affected



```{r, include=TRUE, message=FALSE}

rm(list=ls())
data1 <- read.csv("https://opendata-geohive.hub.arcgis.com/datasets/d9be85b30d7748b5b7c09450b8aede63_0.csv?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D")

n <- nrow(data1)

data1$Date <- as.character(data1$TimeStamp)
data1$Date <- substr(data1$Date, 1, 10)
data1$Date <- as.Date(data1$Date, "%Y/%m/%d")
the.date <- data1$Date[n]

library(sf)
library(tidyverse)
library(raster)
library(dplyr)
library(spData)
library(tmap)
library(csodata)

shp <- cso_get_geo("ac")

a<- data.frame(data1$Date, data1$CountyName, data1$ConfirmedCovidCases)
b <- reshape(a, direction="wide", idvar="data1.Date", timevar="data1.CountyName")



counties_start <- grep("data1.ConfirmedCovidCases.Carlow", colnames(b))
counties_stop <- grep("data1.ConfirmedCovidCases.Wicklow", colnames(b))

counties <- tibble(b[which(b$data1.Date == the.date ), counties_start:counties_stop])



cso <- read.csv("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/counties_population_cso_2016.csv")

counties <- data.frame(r1=names(counties), t(counties))
colnames(counties)[2] <- "cases"
colnames(counties)[1] <- "county_doh"

counties$county_doh <- substring(counties$county_doh,27)
counties$county_doh <- tolower(counties$county_doh)
 


counties$cases <- as.numeric(as.character(counties$cases))
counties[,1] <- sub("cases_", "", counties[,1])
counties$cases <- as.numeric(counties$cases)

county_cases <- merge(cso, counties, by="county_doh")


county_cases$cases_per_mil <- 1000000*county_cases$cases/county_cases$pop

names(shp)[8] <- "county"
shp$county[20]="Dun Laoghaire-Rathdown"
county_cases$county[8]="Dun Laoghaire-Rathdown"

merged_cases <- merge(shp, county_cases, by="county")

tm_shape(merged_cases) + tm_fill(col="cases_per_mil", style = "pretty", title=c(paste("Cases per million", the.date))) + tm_borders() + tm_layout(asp = 1.28)          

```   
                

