---
date: 
 image:
  caption: Cases by Age over last 2 Weeks
  focal_point: Smart
summary: Cases by Age over last 2 Weeks
title: Cases by Age over last 2 Weeks

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(RCurl)

x <- getURL("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/doh_covid_ie_cases_analysis.csv")
data1 <- read.csv(text = x, stringsAsFactors=FALSE)
n <- nrow(data1)
the.date <- data1$date[n]
```

<br><br><br><br>

Below we show the breakdown by age of the infected over the last 2 weeks. The mean cases per million for the total population is shown as the yellow dashed line, as well as the mean excluding children (where incidence may be lower) as the green dashed line. Updated as of `r the.date`.

<br><br><br><br>



```{r, include=TRUE, message=FALSE, warning=FALSE}

library(tidyverse)
library(RCurl)
#install.packages("viridis")  # Install
library("viridis")  

x <- getURL("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/doh_covid_ie_cases_analysis.csv")
data1 <- read.csv(text = x, stringsAsFactors=FALSE)
n <- nrow(data1)

data1$date <- as.Date(data1$date, format= "%d-%b")
the.date <- data1$date[n]


y <- getURL("https://raw.githubusercontent.com/frankmoriarty/covid_ie/master/age_population_cso_2019.csv")
age_population_cso <- read.csv(text = y, stringsAsFactors=FALSE)

totalllcases <- as.numeric(data1$cases_cumul)
age <- c("0-4","05-14","15-24","25-34","35-44","45-54","55-64","65-74", "75-84", "85+")


cases <- as.numeric(c(data1$cases_under_5[which(data1$date == the.date )] - data1$cases_under_5[which(data1$date == the.date -14)] ,
                      data1$cases_5_14[which(data1$date == the.date )] - data1$cases_5_14[which(data1$date == the.date - 14 )],
                      data1$cases_15_24[which(data1$date == the.date )] - data1$cases_15_24[which(data1$date == the.date - 14 )],
                      data1$cases_25_34[which(data1$date == the.date )] - data1$cases_25_34[which(data1$date == the.date - 14 )],
                      data1$cases_35_44[which(data1$date == the.date)]- data1$cases_35_44[which(data1$date == the.date - 14)],
                      data1$cases_45_54[which(data1$date == the.date)] - data1$cases_45_54[which(data1$date == the.date - 14)],
                      data1$cases_55_64[which(data1$date == the.date)] - data1$cases_55_64[which(data1$date == the.date - 14)],
                      data1$cases_65_74[which(data1$date == the.date)] - data1$cases_65_74[which(data1$date == the.date - 14)], data1$cases_75_84[which(data1$date == the.date)] - data1$cases_75_84[which(data1$date == the.date - 14)], data1$cases_85_plus[which(data1$date == the.date)]- data1$cases_85_plus[which(data1$date == the.date - 14)]))

#the cases by age all as numeric

popcso<- age_population_cso$pop_estimate[1:10]      #the population estimates  


popcso.dividedbymillion <- popcso/1000000          #the population estimates divided by million as per formula in notebook



cases1M <- cases/popcso.dividedbymillion         #this gives a string of the cases per one million by age

df <- data.frame(age,cases1M)

the.plot <- ggplot(data=df, aes(x= age, y=cases1M,fill= age)) + geom_bar(stat='identity') +
  scale_fill_viridis(option = "D", discrete = TRUE, guide= FALSE)




total.cases <- (totalllcases[which(data1$date == the.date )] - totalllcases[which(data1$date == the.date -14 )]) #this gives the total cases on the date

totalpop.dividedby1m <- (age_population_cso$pop_estimate[which(age_population_cso$age_group=='cases_all_ages')])/1000000

mean.cases1M<- as.numeric(total.cases)/as.numeric(totalpop.dividedby1m)   #this is population mean for average abline


total.cases15plus <- (totalllcases[which(data1$date == the.date )]-totalllcases[which(data1$date == the.date - 14 )])-  ((data1$cases_under_5[which(data1$date == the.date )]-data1$cases_under_5[which(data1$date == the.date - 14 )])+               (data1$cases_5_14[which(data1$date == the.date )] - data1$cases_5_14[which(data1$date == the.date - 14 )])) #this gave the total amount of cases 15 plus

pop15plus.dividedby1M <- (age_population_cso$pop_estimate[which(age_population_cso$age_group=='cases_age_15_plus')])/1000000    #this was the population 15 plus divided by 1 million as per formula in notebook

mean.cases15plus1M <- total.cases15plus/pop15plus.dividedby1M  #this shows the total cases 15 plus per 1 million people




plot2 <- the.plot +geom_hline(aes(yintercept= mean.cases15plus1M, linetype = "Mean 15-plus"), colour= "green", size=1.25) +
  geom_hline(aes(yintercept=mean.cases1M , linetype = "Mean Total Population"), colour= "yellow", size=1.25) +
  scale_linetype_manual(name = "", values = c(2, 2), 
                        guide = guide_legend(override.aes = list(color = c("green", "yellow"))))
plot3 <- plot2 + labs(title= "Cases by Age over last 2 Weeks",y= "Cases per Million", x = "Age-groups (Yr)")


plot3 +theme(legend.key = element_rect(fill = "lightblue", color = NA), axis.text=element_text(size=8, face = "bold"),
             axis.title=element_text(size=14,face="bold"), plot.title = element_text(size=16, face = "bold"))



```
